### PR TITLE
Refactor to preprocessor

### PR DESCRIPTION
**Pull request by ghost**
Tested with `npm link` and rework-suit. Everything seems to work:
- production builds (asset revving, minifying)
- development builds (livereload)
- variables across files
- `@imports` with rework-npm use the correct relative path now
- partials are now excluded from the output by default

Partials are a part of rework-npm's functionality, so not necessarily something that will be included in every rework setup. But a couple of plugins fail if rework-npm is used and the partials aren't filtered out.

Which is why I've gone for convention over configuration and made all css in the `styles` folder an entry point, and all css in folders below styles a partial (and thus ignored). It can be overridden with the `rework.exclude` option.

see #4

### CODE REVIEW

**Comment by johno** [comment]
This is wonderful, thank you!

**Comment by ghost** [comment]
No problem, thanks for merging! By the way, I haven't updated the tests yet, so that's still a todo.

**Comment by johno** [comment]
Thank you for all your hard work.

No worries, the current build failure I believe is the result of some `ember-cli` dependencies being out of whack (the `package.json` for this addon currently specifies `ember-cli@0.1.2` :blush:). I'll run through and update the addon,that may fix the build on travis.

**Comment by johno** [comment]
Just opened PR #6 which updates `ember-cli` and makes the tests pass again, locally anyway. Still waiting for Travis CI.

**Comment by ghost** [comment]
> Thank you for all your hard work.

No problem, glad to help! I'll do some further testing here, let you know if anything comes up.

**Comment by johno** [comment]
Now published to npm as `ember-cli-rework@1.0.0`.

**Pull request merged**
